shift-heading-level-by: -1
filters:
- /commonhaus/filters/agreement-form.lua
include-in-header:
- /commonhaus/content/header-agreement.tex
toc: false
variables:
  website: https://www.commonhaus.org/
