from: gfm+emoji+alerts
reader: gfm+emoji+alerts
file-scope: true
filters:
- /commonhaus/filters/alerts.lua
- /commonhaus/filters/fix-links.lua
include-in-header:
- /commonhaus/content/header.tex
include-after-body:
- /commonhaus/content/afterBody.tex
metadata-file: CONTACTS.yaml
number-sections: true
pdf-engine: lualatex
pdf-engine-opts:
  - '-shell-escape'
template: /commonhaus/content/commonhaus-eisvogel
variables:
  geometry: margin=1in
  colorlinks: true
  listings: true
  hyperrefoptions:
  - linktoc=all
  - pdfencoding=unicode
  - linktocpage
  - bookmarks=true
  - bookmarksnumbered=true
  - bookmarksopen
  website: https://www.commonhaus.org/
